version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rentcheck_postgres
    environment:
      POSTGRES_DB: rentcheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rentcheck123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: